Support files with mixed newlines
Instagram/LibCST pull request #1007
Opened 2023-08-30 11:38 UTC by MichaReiser

## Summary

This PR fixes an issue in LibCST native where it failed to parse a file that uses mixed `\r` and `\n` or `\r` and `\r\n` newlines. 

It also replaces the Regex to find all newlines with a simple call to `memchr`. This should be much faster because it doesn't require the overhead of a full regex automata. 

## Test Plan

Added a new unit test

> **Note**: Replacing all Regex usages in LibCST could result in a huge performance boost because thread locals in Rust are [slow](https://matklad.github.io/2020/10/03/fast-thread-locals-in-rust.html) (or not as fast as they could be) AND most regex are simple and can be replaced with some simple lexing on the string slice directly

2023-08-30 12:13 UTC, MichaReiser commented on native/libcst/src/tokenizer/whitespace_parser.rs
> -            lines: input.split_inclusive(default_newline).collect(),
This incorrectly assumed that a file only uses one kind of line break, resulting in some lines not being split.

2023-08-30 12:19 UTC, MichaReiser commented on native/libcst/src/tokenizer/whitespace_parser.rs
> +        let mut lines = Vec::new();
A possible optimisation is to initialize the Vec with `input.len() / 88` (or 100 or 120, depending on how defensive we want to be). This turned out to improve performance for ruff.

2023-09-02 08:12 UTC, zsol requested changes
LGTM, but I'd like to have a unit test for `Config::new` before merging

2023-09-02 08:12 UTC, zsol commented on native/libcst/src/tokenizer/whitespace_parser.rs
> +                && input.as_bytes().get(newline_position + 1).copied() == Some(b'\n')
nit: can we get away without calling `.copied()`?

2023-09-02 08:12 UTC, zsol commented on native/libcst/src/tokenizer/whitespace_parser.rs
> +        let mut lines = Vec::new();
Can you please add a simple unit test for the new logic in this file as well?

2023-09-02 08:45 UTC, MichaReiser commented on native/libcst/src/tokenizer/whitespace_parser.rs
> +            lines,
`has_trailing_newline` may need fixing too, to correctly handle `\r` endings but I'll leave this for another PR

2023-09-02 08:55 UTC, zsol approved these changes

2023-09-02 08:56 UTC, zsol commented
Thank you!

2023-09-02 08:56 UTC, merged