Issue393
Instagram/LibCST pull request #394
Opened 2020-09-24 21:58 UTC by cdonovick

## Summary
closes #393  by extending ExpressionContextVisitor

## Test Plan
Adds basic tests for the extension

2020-09-24 22:06 UTC, cdonovick commented
Guess I should have ran all tests not just ones I edited.

Seems like this will have more widespread effects than I have anticipated. If you would accept this PR given passing test I would take stab at updating the broken ones.

2020-09-26 17:48 UTC, jimmylai requested changes
This change looks good, just needs to fix the failing tests.
You can run `tox -e autofix` to fix the formatting error in lint CI job.

2020-09-26 17:48 UTC, jimmylai commented on libcst/metadata/expression_context_provider.py
> +            decorator.visiet(self)
This is a typo.
```suggestion
            decorator.visit(self)
```

2020-09-26 17:51 UTC, jimmylai commented on libcst/metadata/tests/test_expression_context_provider.py
> +        wrapper = MetadataWrapper(parse_module("class Foo: pass"))
To make the test comprehensive, let's also test the name of base classes and some names in the class body.

2020-09-26 17:53 UTC, jimmylai commented on libcst/metadata/expression_context_provider.py
> +    def visit_FunctionDef(self, node: cst.FunctionDef) -> Optional[bool]:
The `returns` of a FunctionDef can also have some names.
Let's also visit it and add a test case for it.
https://libcst.readthedocs.io/en/latest/nodes.html#libcst.FunctionDef

2020-09-29 16:45 UTC, jimmylai approved these changes
Looks great!

2020-09-29 16:45 UTC, merged

2020-09-29 21:23 UTC, cdonovick commented
@jimmylai Could you create a new release on pypi?  Thanks.

2020-09-30 16:08 UTC, jimmylai commented
@zsolt plans to make another release after the pending PRs are merged.
I'm reviewing them now.

2020-09-30 16:44 UTC, zsol commented
Wrong Zsolt :) but yes, I expect to make a new release tomorrow.