fix is_annotation for types used in classdef base and assign value
Instagram/LibCST pull request #406
Opened 2020-10-21 02:27 UTC by luciawlli

## Summary
fix is_annotation for types used in classdef base and assign value
discussion
## Test Plan
tox -e py37
tox -e autofix

2020-10-21 08:12 UTC, zsol requested changes

2020-10-21 08:12 UTC, zsol commented on libcst/metadata/scope_provider.py
> +    def visit_Assign_value(self, original_node: cst.Assign) -> None:
```suggestion
    def visit_Assign_value(self, node: cst.Assign) -> None:
```

2020-10-21 08:12 UTC, zsol commented on libcst/metadata/scope_provider.py
> +    def leave_ClassDef_bases(self, node: cst.ClassDef) -> None:
```suggestion
    def leave_ClassDef_bases(self, original_node: cst.ClassDef) -> None:
```

2020-10-21 08:12 UTC, zsol commented on libcst/metadata/scope_provider.py
> +        self.__ignore_annotation: bool = False
This should probably be a stack or a counter instead of a simple bool to keep track of nesting. Let's add a nested test case while we're at it.

2020-10-21 08:12 UTC, zsol commented on libcst/metadata/scope_provider.py
> +        ):
We still want to do the work in `_handle_string_annotation` for these cases, with the only difference being `Access` nodes should have `is_annotation=False`.

2020-10-21 18:58 UTC, jimmylai reviewed
The logic in `visit_Call` also needs to be updated.
The Aug of TypeVar and NewType are not actually Annotation.

2020-10-21 18:58 UTC, jimmylai commented on libcst/metadata/scope_provider.py
> +
Handle Assign differently doesn't seem right.
We should only consider the is_annotation for access in Annotation node (`__in_annotation` already takes case that).

2020-10-28 11:44 UTC, zsol approved these changes

2020-10-28 11:48 UTC, merged